import animate from 'tailwindcss-animate';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        adminLayout: {
          grey: {
            10: '#F7F9FC',
            20: '#667085',
            30: '#5D6679',
            40: '#FFFFFF',
            50: '#FAFAFA',
            100: '#F5F5F5',
            200: '#E5E5E5',
            250: '#E8F1FD',
            300: '#D9D9D9',
            400: '#A3A3A3',
            500: '#737373',
            600: '#5D6679',
            700: '#404040',
            800: '#262626',
            900: '#171717',
          },
          primary: {
            10: '#0F50AA',
            50: '#E3F2FF',
            100: '#C9E4FF',
            200: '#A0D2FF',
            300: '#75BFFF',
            400: '#4AAEFF',
            500: '#1570EF',
            600: '#1366D9',
            700: '#1976D2',
            800: '#1565C0',
            900: '#0D47A1',
            DEFAULT: 'hsl(var(--primary))',
            foreground: 'hsl(var(--primary-foreground))',
          },
          red: {
            50: '#FFE3E3',
            100: '#FFBDBD',
            200: '#FF9B9B',
            300: '#F86A6A',
            400: '#EF4E4E',
            500: '#E12D39',
            600: '#CF1124',
            700: '#AB091E',
            800: '#8A041A',
            900: '#610316',
          },
          warning: {
            50: '#FFF8E1',
            100: '#FFECB3',
            200: '#FFE082',
            300: '#FFD54F',
            400: '#FFCA28',
            500: '#FFC107',
            600: '#FFB300',
            700: '#FFA000',
            800: '#FF8F00',
            900: '#FF6F00',
          },
          success: {
            50: '#E3F9E5',
            100: '#C1EAC5',
            200: '#A3D9A5',
            300: '#7BC47F',
            400: '#57AE5B',
            500: '#3F9142',
            600: '#2F8132',
            700: '#207227',
            800: '#0E5814',
            900: '#05400A',
          },
          dashboard: {
            50: '#EEF0F2',
            100: '#383E49',
            200: '#0D824B',
            300: '#B6E9D1',
            400: '#858D9D',
            500: '#667085',
            600: '#5D6679',
          },
          frontdesk: {
            bgLightPeach: '#FEF4E6',
            bgLightBlue: '#E8F1FD',
            bgErrorLight: '#FEECEB',
            bgSuccessLight: '#E7F8F0',
            primaryOrange: '#F9A63A',
            primaryBlue: '#448DF2',
            errorRed: '#F36960',
            successGreen: '#41C588',
          },

          background: 'hsl(var(--background))',
          foreground: 'hsl(var(--foreground))',
          card: {
            DEFAULT: 'hsl(var(--card))',
            foreground: 'hsl(var(--card-foreground))',
          },
          popover: {
            DEFAULT: 'hsl(var(--popover))',
            foreground: 'hsl(var(--popover-foreground))',
          },
          secondary: {
            DEFAULT: 'hsl(var(--secondary))',
            foreground: 'hsl(var(--secondary-foreground))',
          },
          muted: {
            DEFAULT: 'hsl(var(--muted))',
            foreground: 'hsl(var(--muted-foreground))',
          },
          accent: {
            DEFAULT: 'hsl(var(--accent))',
            foreground: 'hsl(var(--accent-foreground))',
          },
          destructive: {
            DEFAULT: 'hsl(var(--destructive))',
            foreground: 'hsl(var(--destructive-foreground))',
          },
          border: 'hsl(var(--border))',
          input: 'hsl(var(--input))',
          ring: 'hsl(var(--ring))',
          chart: {
            1: 'hsl(var(--chart-1))',
            2: 'hsl(var(--chart-2))',
            3: 'hsl(var(--chart-3))',
            4: 'hsl(var(--chart-4))',
            5: 'hsl(var(--chart-5))',
          },
        },
        root: {
          primary: {
            50: '#2F7BEB',
            100: '#B9BDC7',
            400: '#2F83B2',
            500: '#07689F',
            600: '#043E5F',
          },
          gray: {
            100: '#F9F9F9',
            200: '#EFEFEF',
            300: '#D9D9D9',
            400: '#A6A6A6',
            500: '#565656',
            white: '#FFFFFF',
          },
          state: {
            Error_Light: '#EA0205',
            Error_Dark: '#A80102',
            Alert: '#FDFF83',
            Accent: '#FF6C01',
            Success_Light: '#E8F5E4',
            Success_Dark: '#4C9839',
          },
        },
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
      },
      borderRadius: {
        sm: 'calc(var(--radius) - 4px)',
        md: 'calc(var(--radius) - 2px)',
        lg: 'var(--radius)',
      },
      fontFamily: {
        poppins: ['Poppins', 'sans-serif'],
      },
    },
  },
  plugins: [animate],
};
